### PR TITLE
Add the SCSS and Coffee-Script support

### PR DESCRIPTION
**Pull request by dreampuf**
I love the SCSS and Coffee-Script two things that make me happy in coding.
Please pull this request.

### CODE REVIEW

**Comment by willkg** [comment]
Looks like the tests are failing, so that should get looked at first.

The code looks ok to me. It'd probably be better to rework the code so that adding support for additional systems is a modular thing.

**Comment by dreampuf** [comment]
Fixed this case.

**Comment by rehandalal** [comment]
@dreampuf thanks for fixing the test!

I'll look at reworking this so that it's a little more DRY/modular, before merging it.

**Comment by rehandalal** [comment]
Merged. Thanks!

**Comment by rehandalal** [comment]
70ad89c0a6c0308fe66efc34f2520aa62e4f856a

**Pull request closed without merging**
