### PR TITLE
Add support for Python 3.3

### PR DESCRIPTION
**Pull request by tonyseek**
@rehandalal Please review it. :smile:

### CODE REVIEW

**Comment by ghost** [comment]
+1.

**Comment by rehandalal** [comment]
Sorry, will review this tomorrow.

**Comment by rehandalal** [comment]
Looks good, I'll merge this shortly. Thanks @tonyseek!

**Comment by rehandalal** [comment]
Merged.
b635cf52d1c9133c748aab7465edd7caef48e433

**Comment by tonyseek** [comment]
:smile:

**Pull request closed without merging**
