### PR TITLE
make the flask-funnel support the sourcemap (use the original url path)

### PR DESCRIPTION
**Pull request by dreampuf**
Now you could use the `sass --sourcemap` to generate the css that include the map tag.
In modern develop tools will use these information to help developer.

### CODE REVIEW

**Comment by rehandalal** [comment]
Tests are failing. Not sure why yet.

**Comment by dreampuf** [comment]
https://travis-ci.org/rehandalal/flask-funnel/jobs/8707279#L439

Seem like werkzeug didn't support Py2.5 anymore. Question is the version of it has been determine use `Flask==0.9`, but in the Flask's dependences didn't determine the special version.

http://lucumr.pocoo.org/2013/6/13/werkzeug-and-flask-releases/

> Bad news for you if you're on 2.5: support for your Python version is gone. That was necessary to make the Python 3 port go forward. Python 2.5 by now is nearly 7 years old, it's time to move on.

```
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/usr/lib/python2.5/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.5/distutils/dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/distribute-0.6.34-py2.5.egg/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/distribute-0.6.34-py2.5.egg/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/distribute-0.6.34-py2.5.egg/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib/python2.5/unittest.py", line 767, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.5/unittest.py", line 794, in parseArgs
    self.createTests()
  File "/usr/lib/python2.5/unittest.py", line 800, in createTests
    self.module)
  File "/usr/lib/python2.5/unittest.py", line 565, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.5/unittest.py", line 533, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/rehandalal/flask-funnel/flask_funnel/__init__.py", line 2, in <module>
    from flask_funnel import manager
  File "/home/travis/build/rehandalal/flask-funnel/flask_funnel/manager.py", line 9, in <module>
    from flask import current_app
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/home/travis/virtualenv/python2.5/lib/python2.5/site-packages/werkzeug/exceptions.py", line 75
    class HTTPException(Exception):
        ^
SyntaxError: invalid syntax
```

Other some testcases need to be fix with new generate url rules, I will do this job later.

**Comment by willkg** [comment]
I concur: we should just ditch support for Python 2.5.

Also, we should tweak the Travis file to test with both Flask 0.9 and Flask 0.10.1. I can do that in a separate PR if that helps.

**Comment by dreampuf** [comment]
Done.

**Comment by rehandalal** [comment]
Merged! Thanks!!

**Pull request closed without merging**
